/** Additive v1 contract; publication and actual compatible bridge installation are separate. */
export type CollaborationAuthor = {kind:'owner'} | {kind:'bot';botId:string;contextId:string|null;threadId:string;turnId:string};
export type CollaborationRoom = {id:string;type:'pair'|'group';name:string;members:string[];revision:number;held:boolean;createdAt:string;operationId:string;order?:string};
export type CollaborationPost = {id:string;roomId:string;author:CollaborationAuthor;kind:'info'|'question'|'task'|'result';text:string;recipients:string[];expectation:'none'|'result';workId:string|null;requestId:string|null;rootId:string|null;operationId:string;createdAt:string;order?:string;result?:{deliveryId:string;outcome:'completed'|'blocked';resultIds:string[]}};
export type CollaborationDelivery = {id:string;botId:string;roomId:string;postId:string;contextId:string;state:'queued'|'dispatching'|'uncertain'|'accepted'|'rejected'|'completed';turnId:string|null;error:string|null;terminalStatus:string|null;waitReason:string|null;resultState:'available'|'pending'|'missing'|'not-requested'};
export type ExecutionSettings = {model:string;effort:string|null;serviceTier:string;mode:'default'|'plan'};
export type TurnConfiguration = {id?:string;botId?:string;threadId:string;turnId:string|null;requested:ExecutionSettings|null;effective:null;confirmation:'unknown'|'requested'|'accepted-request';source:string;capturedAt?:string;settingsRevision?:number;evidence?:string;acknowledgedAt?:string};
export type ExecutionConfiguration = {version:1;contextId:string;threadId:string|null;active:TurnConfiguration|null;selected:TurnConfiguration|null;future:{revision:number;requested:ExecutionSettings;confirmation:'unknown'|'saving'|'unconfirmed'|'saved-for-next-turn';executionMode:'foreground'|'collaboration';planIntent:'not-applicable'|'foreground-next-human-start'|'default';operationId?:string;pendingOperationIds?:string[]};history:TurnConfiguration[];nextCursor:string|null};
export type CollaborationContext = {id:string;botId:string;roomId:string;threadId:string|null;provisioning:'prepared'|'dispatching'|'bound'|'rejected'|'uncertain';activeTurnId:string|null;status:'idle'|'running'|'unknown';paused:boolean;revision:number;error:string|null;config:TurnConfiguration|null;goal:{threadId:string|null;status:import('./codex-protocol/v2/ThreadGoalStatus').ThreadGoalStatus|'unknown'|'none'};order?:string};
export type CollaborationResult = {id:string;botId:string;roomId:string;deliveryId:string;sourceBotId:string;contextId:string;threadId:string;turnId:string;workId:string|null;requestId:string|null;rootId:string|null;operationId:string;outcome:'completed'|'blocked';text:string;references:string[];createdAt:string;promotion:{id:string;operationId:string;boundary:'dependency'|'milestone'|'human';dependencyId:string|null;createdAt:string;state:'queued'|'accepted';turnId?:string;evidence?:string}|null;order?:string};
export type CollaborationRecentParams = {cursor?:string|null;limit?:number;view?:'latest'|'older'|'newer'};
export type CollaborationPage<T> = {items:T[];nextCursor:string|null;complete:boolean;view?:'latest'|'older'|'newer';highWater?:string;olderCursor?:string|null;newerCursor?:string};
export type CollaborationPostParams = {roomId:string;kind:CollaborationPost['kind'];text:string;recipients?:string[];expectation?:'none'|'result';workId?:string;requestId?:string;rootId?:string;/** Owner-only original active turn IDs, keyed by addressed bot. */steer?:Record<string,string>};
export type CollaborationResource = {id:string;botId:string;contextId:string;effectId:string;operationId:string;state:'held'|'released';createdAt:string;releasedAt?:string;releaseOperationId?:string};
