import test from 'node:test';
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store } from './store.mjs';
import { BotRuntime } from './runtime.mjs';

test('runtime history reads are scoped, nonmutating, conditional and recover full native details', async (t) => {
  const root = await mkdtemp(join(tmpdir(), 'bot-history-view-'));
  const store = new Store(join(root, 'state.sqlite')), codex = new EventEmitter(), calls = [];
  const item = { type: 'commandExecution', id: 'tool', command: 'synthetic', aggregatedOutput: 'x'.repeat(100000), status: 'completed' };
  codex.call = async (method, params) => { calls.push({ method, params }); if (method === 'thread/resume') return {}; return { data: [{ id: 'turn', items: [item], status: 'completed', startedAt: 1 }], nextCursor: null }; };
  const runtime = new BotRuntime({ store, codex, root });
  t.after(async () => { store.close(); await rm(root, { recursive: true, force: true }); });
  const bot = store.saveBot({ id: 'bot', threadId: 'thread', name: 'Synthetic', cwd: root, slug: 'synthetic', archived: false, updatedAt: 'stable' });
  const read = (method, params = {}, botId = bot.id) => runtime.handle({ method, botId, params });
  const page = await read('history.view'); assert.equal(page.entries[0].item, null);
  assert.ok(calls.some((call) => call.method === 'thread/resume'), 'ensure stream subscription follows existing history behavior');
  const before = calls.length; assert.equal((await read('history.view', { revision: page.revision })).kind, 'unchanged'); assert.equal(calls.length, before);
  const event = runtime.emitEvent('codex', { method: 'item/commandExecution/outputDelta', params: { turnId: 'turn', itemId: 'tool', delta: 'new' } }, bot.id);
  const replay = await read('history.view', { revision: page.revision, after: page.eventCursor }); assert.equal(replay.kind, 'events'); assert.equal(replay.events[0].seq, event.seq);
  const detail = await read('history.detail', { turnId: 'turn', itemId: 'tool' }); assert.ok(detail.nextOffset); const scans = calls.length;
  await read('history.detail', { turnId: 'turn', itemId: 'tool', offset: detail.nextOffset, version: detail.version }); assert.equal(calls.length, scans);
  const unchanged = await read('history.detail', { turnId: 'turn', itemId: 'tool', knownVersion: detail.version }); assert.equal(unchanged.notModified, true);
  await assert.rejects(read('history.view', {}, 'missing-bot'), /found|Unknown|exist/i);
  assert.ok(calls.every((call) => ['thread/resume', 'thread/turns/list'].includes(call.method)));
});

test('large native events are compact before storage/wire; real client refreshes only open detail and settles completion', async (t) => {
  const { runtime: browserRuntime } = await import('../tests/helpers/load-ts.mjs');
  const { IDBKeyRange } = await import('fake-indexeddb');
  const root = await mkdtemp(join(tmpdir(), 'bot-live-bound-')), store = new Store(join(root, 'state.sqlite')), codex = new EventEmitter();
  let nativeItem = { type: 'commandExecution', id: 'tool', command: 'synthetic', aggregatedOutput: 'initial', status: 'inProgress' }, scans = 0;
  codex.call = async () => { scans++; return { data: [{ id: 'turn', items: [nativeItem], status: nativeItem.status === 'inProgress' ? 'inProgress' : 'completed', startedAt: 1 }], nextCursor: null }; };
  const runtime = new BotRuntime({ store, codex, root });
  t.after(async () => { store.close(); await rm(root, { recursive: true, force: true }); });
  store.saveBot({ id: 'bot', threadId: 'thread', name: 'Synthetic', cwd: root, slug: 'synthetic', archived: false, updatedAt: 'stable' }); runtime.loaded.add('thread');
  const env = browserRuntime({ IDBKeyRange, localStorage: { getItem: () => null, setItem() {} } });
  const { BotsClient } = env.load('app/bots/client.ts'), { BotTimeline } = env.load('app/bots/timeline-controller.ts');
  const client = new BotsClient(); client.owner = 'synthetic-owner'; client.online = true;
  const requests = []; client.rpc = async (method, botId, params) => { requests.push(method); return JSON.parse(JSON.stringify(await runtime.handle({ method, botId, params }))); };
  const timeline = new BotTimeline(client.owner, 'bot', client, { read: async () => null, write: async () => {} });
  client.events.add((event) => timeline.receive(event));
  const events = []; runtime.on('event', (event) => { events.push(event); client.receive({ type: 'event', event: JSON.parse(JSON.stringify(event)) }); });
  await timeline.refresh(); const descriptor = timeline.getSnapshot().entries[0];
  // Closed output: full native item remains recoverable, no page/detail request.
  nativeItem = { ...nativeItem, aggregatedOutput: 'large synthetic tool output\n'.repeat(50000) };
  const rawItem = { method: 'item/completed', params: { turnId: 'turn', item: { ...nativeItem, status: 'completed' } } };
  runtime.emitEvent('codex', rawItem, 'bot');
  const rawDelta = { method: 'item/commandExecution/outputDelta', params: { turnId: 'turn', itemId: 'tool', delta: 'next output'.repeat(100000) } };
  for (let i = 0; i < 10; i++) runtime.emitEvent('codex', rawDelta, 'bot');
  await new Promise((r) => setTimeout(r, 300)); assert.deepEqual(requests, ['history.view']);
  assert.ok(events.every((event) => Buffer.byteLength(JSON.stringify(event)) < 16384));
  assert.ok(store.replay(0).every((event) => !JSON.stringify(event).includes(rawDelta.params.delta)));
  const unsubscribe = timeline.subscribeDetail(descriptor, () => {}); await timeline.detail(descriptor); const before = scans;
  nativeItem = { ...nativeItem, status: 'completed', aggregatedOutput: nativeItem.aggregatedOutput + '\nFINAL AUTHORITATIVE OUTPUT' };
  runtime.emitEvent('codex', { method: 'item/completed', params: { turnId: 'turn', item: nativeItem } }, 'bot');
  runtime.emitEvent('codex', { method: 'turn/completed', params: { turn: { id: 'turn', status: 'completed', items: [] } } }, 'bot');
  await new Promise((r) => setTimeout(r, 1300));
  assert.match(timeline.detailItem(descriptor).aggregatedOutput, /FINAL AUTHORITATIVE OUTPUT$/);
  assert.equal(timeline.detailItem(descriptor).status, 'completed'); assert.equal(timeline.getSnapshot().entries[0].status, 'completed');
  assert.equal(scans - before, 1, 'one coalesced full native lookup for open final detail');
  const rawBytes = Buffer.byteLength(JSON.stringify(rawItem)) + 10 * Buffer.byteLength(JSON.stringify(rawDelta));
  const wireBytes = events.slice(0, 11).reduce((n, event) => n + Buffer.byteLength(JSON.stringify(event)), 0);
  console.log(JSON.stringify({ scenario: 'large closed-tool item plus 10 output deltas', nativePayloadBytes: rawBytes, compactWireBytes: wireBytes, persistedReplayBytes: Buffer.byteLength(JSON.stringify(store.replay(0))), closedDetailRequests: 0, openFinalNativeScans: scans - before }));
  unsubscribe(); await timeline.dispose();
});
