export type SnapshotRecipient = { version:1; kind:'dawar-snapshot-recipient'; publicKey:string; privateKey:string; fingerprint:string };
export type SealedSnapshot = { version:1; kind:'dawar-application-snapshot-sealed'; sourceOrigin:string; recipientFingerprint:string; contentSHA256:string; ephemeralPublicKey:string; iv:string; ciphertext:string };
export function newSnapshotRecipient():Promise<SnapshotRecipient>;
export function snapshotRecipient(publicKey:string):Promise<{key:CryptoKey; fingerprint:string}>;
export function sealApplicationSnapshot(snapshot:string,recipient:string,sourceOrigin:string):Promise<SealedSnapshot>;
export function unsealApplicationSnapshot(envelope:SealedSnapshot,recipient:SnapshotRecipient,expectedOrigin:string):Promise<{snapshot:string;sha256:string;sourceOrigin:string;sourceAuthenticationEstablished:false}>;
export type ApplicationReadBinding = {sourceOrigin:string;captureId:string;requestId:string;sequence:number;commandSHA256:string;
  freeze:{sourceId:string;operationId:string;epoch:number;generation:number;expiresAt:number}};
export type SealedApplicationRead = ApplicationReadBinding & {version:1;kind:'dawar-application-read-sealed';recipientFingerprint:string;
  contentSHA256:string;ephemeralPublicKey:string;iv:string;ciphertext:string};
export function applicationReadBinding(value:ApplicationReadBinding):ApplicationReadBinding;
export function sealApplicationRead(payload:unknown,recipient:string,binding:ApplicationReadBinding):Promise<SealedApplicationRead>;
export function unsealApplicationRead(envelope:SealedApplicationRead,recipient:SnapshotRecipient,expected:ApplicationReadBinding):Promise<{payload:unknown;sourceAuthenticationEstablished:false}>;
